# Generated by Django 3.2.4 on 2021-06-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hometeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('goal_hometeam', models.IntegerField()),
                ('goal_awayteam', models.IntegerField()),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.hometeam')),
            ],
        ),
        migrations.CreateModel(
            name='Awayteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.hometeam')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.match')),
            ],
        ),
    ]
