# Generated by Django 3.2.4 on 2021-06-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awayteam',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteam', to='pronos.match'),
        ),
    ]
