# Generated by Django 3.2.4 on 2021-06-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0004_alter_awayteam_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awayteam',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pronos.match'),
        ),
    ]
