# Generated by Django 3.2.4 on 2021-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0006_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goal_awayteam',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goal_hometeam',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
