# Generated by Django 3.2.4 on 2021-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0007_auto_20210626_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='prono_awayteam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='prono_hometeam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
