# Generated by Django 3.2.4 on 2021-06-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0008_auto_20210627_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awayteam',
            name='hometeam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pronos.hometeam'),
        ),
    ]
