# Generated by Django 3.2.4 on 2021-06-27 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pronos', '0009_alter_awayteam_hometeam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awayteam',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.hometeam'),
        ),
        migrations.AlterField(
            model_name='awayteam',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.match'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.awayteam'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.hometeam'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronos.match'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
