# Generated by Django 3.2.4 on 2021-06-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0013_userteam_userteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='prono_awayteam',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='prono_hometeam',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
