# Generated by Django 3.2.4 on 2021-06-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0015_bet_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
