# Generated by Django 3.2.4 on 2021-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0016_delete_userscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
