# Generated by Django 3.2.4 on 2021-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0017_alter_bet_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
