# Generated by Django 3.2.4 on 2021-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0018_alter_bet_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
