# Generated by Django 3.2.4 on 2021-07-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0019_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
